name: Update PR on main repo w/ latest VSCode build
on: workflow_dispatch

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ true && 'one' || 'two' }}"
      - run: echo "${{ false && 'one' || 'two' }}"
