name: Update PR on main repo w/ latest VSCode build
on: workflow_dispatch

env:
  CDK_DIR: ${{ 'bal' }}${{ 'rpo' }}

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "tfCmd=terraform${{ inputs.IAC_TOOL == 'cdktf' && format(' -chdir={0}', env.CDK_DIR)" }}" >> "$GITHUB_ENV"
      - run: env
